### ISSUE TITLE
Unknown command: 'maintenance' - setup problems

### ISSUE THREAD

**Issue by jplehmann** [shanx/django-maintenancemode#12]
Just trying this out, and pip installed the hot new version 0.11.  But I can't tell that it's working at all?  I feel like I'm making a rookie mistake but the instructions are so simple.

This shows what I've done:
```
(mm)...]$ pip freeze | grep maintenance
django-maintenancemode==0.11.0

(mm)...]$ git diff .
diff --git a/mysite/mysite/settings/base.py b/mysite/mysite/settings/base.py
index 863ab39..7e0f61e 100644
--- a/mysite/mysite/settings/base.py
+++ b/mysite/mysite/settings/base.py
@@ -124,12 +124,26 @@ MIDDLEWARE_CLASSES = (
     'django.contrib.auth.middleware.AuthenticationMiddleware',
+    'maintenancemode.middleware.MaintenanceModeMiddleware', # after Auth. Middleware
     'django.contrib.auth.middleware.SessionAuthenticationMiddleware',
 )
 
+# Setting this variable to ``True`` activates the middleware.
+# But can also activate: python ./manage.py maintenance <on|off>
+MAINTENANCE_MODE = True
+
+# Sequence of URL path regexes to exclude from the maintenance mode.
+# Default: ()
+# TODO: could put /resources here, etc. and probably anything that doesn't 
+# really depend on the database.
+#MAINTENANCE_IGNORE_URLS = (
+#    r'^/docs/.*',
+#    r'^/contact'
+#)
+
 
(mm)...]$ ./manage.py maintenance on
Unknown command: 'maintenance'
Type 'manage.py help' for usage.
```
I also tried migrating, not that I expected it needed it.

What's going on?

**Comment by bashu** [comment]
oops, forgot to update docs you'll need to add ``maintenancemode`` to ``INSTALLED_APPS`` in your project's ``settings.py`` file:
```python
INSTALLED_APPS = (
    ...
    'maintenancemode',
)
```

**Comment by jplehmann** [comment]
Thank you, this was a complete noob issue and something I could have
thought of. But like on the road, when someone starts giving me directions
I stop thinking for myself. :)

**Comment by jplehmann** [comment]
@bashu sorry to bother again, but whether I set the var to `True` in my settings, or I use the manage.py command with `on` (which now does not error, but produces no output), I do not appear to get routed to a 503 page.  I am not logged in, and I have tried this locally both ways, as well as in production (heroku). I am using Django 1.8.

**Comment by bashu** [comment]
hey, can you post your settings.py? have you tried ``example`` project?

**Comment by jplehmann** [comment]
Trying to get `example` working.  I have:
1. created venv
2. installed requirements
3. export DJANGO_SETTINGS_MODULE='example.settings'
4. any attempt to run manage fails: ~/git/django-maintenancemode]$
example/manage.py  with `ImportError: No module named example.settings`

I actually did get it to run if I am within the example dir, but I don't
think this is right because I have problems later with it finding other
things.


Regarding my settings within my app, see my initial issue description for
the relevant parts.  Here's a gist of the whole thing:
https://gist.github.com/jplehmann/17981d1eabb3d2228809  There's a little
more in prod/local configs but I don't think it's relevant.

thanks!

**Comment by bashu** [comment]
all you need to run it as ``python example/manage.py runserver`` see example/README.md

**Comment by jplehmann** [comment]
I take it you're staying my step 3 is unnecessary.  I should have clarified -- if I unset the variable I get the same error.  I can find no permutation which is correct, including unset.

**Comment by bashu** [comment]
have you tried to run example as described here https://github.com/shanx/django-maintenancemode/blob/develop/example/README.rst ?

**Comment by bashu** [comment]
@jplehmann you right I need to make sure ``example``  works without ``PYTHONPATH`` manipulations

**Comment by jplehmann** [comment]
Okay on our other thread of convo (my actually app) -- I have debugged it locally and discovered that it's working fine there -- it was my INTERNAL_IPS, so all is good.

However, in production on Heroku, it is NOT working, and I haven't determined the cause yet. Might be because of the way it attempts to modify the lockfile, I'm going to see if that's getting set.  I welcome any ideas here.

**Comment by jplehmann** [comment]
Yes, it appears to be failing to create a lockfile after I run maintenance on.  I think it should be creating it here: `/app/.heroku/python/lib/python2.7/site-packages/maintenancemode/`.    I will try deploying with the hardcoded setting and see if that works for now, and create a new issue.

**Comment by bashu** [comment]
or set ``MAINTENANCE_LOCKFILE_PATH`` option to a different path, for reference https://github.com/shanx/django-maintenancemode/blob/develop/maintenancemode/conf.py#L11

**Comment by jplehmann** [comment]
For anyone who finds this in the future, I remembered why this approach will not work on heroku. Any execution of `heroku run manage.py` will be run on a separate worker dyno, not the web one.  I think a good alternative would be a staff-authenticated view which togged the maintenance status by adding/removing the file.

**Comment by bashu** [comment]
feel free to post a bug report
