### ISSUE TITLE
Check on maintenance status

### ISSUE THREAD

**Issue by sabinem** [shanx/django-maintenancemode#18]
Yan you please help me on how to check the status that the site is in. I recently forgot to turn off maintenance mode. I would like to see it even as an admin, that the site is currently in maintenance mode, but I could not figure out how to get the status. 

This is what I tried: 
       >>> from maintenancemode import utils as maintenance
       >>> maintenance.status
      Traceback (most recent call last):
      File "<console>", line 1, in <module>
      AttributeError: 'module' object has no attribute 'status'

What did I do wrong?

**Comment by bashu** [comment]
Hey,

should be
```python
from maintenancemode import utils as maintenance
maintenance.status()  # call the function
```

**Comment by sabinem** [comment]
Thank you, but I get the same result for the function:
>>> from maintenancemode import utils as maintenance
>>> maintenance.status()
Traceback (most recent call last):
  File "<console>", line 1, in <module>
AttributeError: 'module' object has no attribute 'status'

**Comment by bashu** [comment]
Hey,

Can you check what version do you have installed ?
```shell
pip freeze | grep maintenancemode
```
to make sure it's latest
```shell
pip install -U django-maintenancemode
```

**Comment by sabinem** [comment]
Thanks a lot, that was it. I was running on:

django-maintenancemode==0.11.0

I updated and now it is working.

      So thanks a lot

           Sabine



On Wed, Dec 2, 2015 at 12:59 PM, Basil Shubin <notifications@github.com>
wrote:

> Hey,
>
> Can you check what version do you have installed ?
>
> pip freeze | grep maintenancemode
>
> to make sure it's latest
>
> pip install -U django-maintenancemode
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/shanx/django-maintenancemode/issues/18#issuecomment-161271709>
> .
>



-- 
Sabine Maennel
Leimbachstr. 223
8041 Zürich
Tel. +41 (0) 43 53 778 74
Mathematikerin / Softwareingenieurin
sabine.maennel@gmail.com
Startup: http://mentoki.com
Facebook: https://www.facebook.com/internetteachers
