### ISSUE TITLE
limit staff users too!

### ISSUE THREAD

**Issue by aliva** [shanx/django-maintenancemode#19]
current implementation let's any staff user access pages ([link](https://github.com/shanx/django-maintenancemode/blob/develop/maintenancemode/middleware.py#L39))

``` python
if hasattr(request, 'user') and request.user.is_staff:
    return None
```

I think it would better to have a custom queryset to limit some staff users, or at least fully disable access for all user (staff or not staff)

**Comment by bashu** [comment]
@aliva fixed in 1b5acb7e8466a877404d1b6ccdd9526a7d2b89c0
