### ISSUE TITLE
Lock file location should be configurable in django settings.py file

### ISSUE THREAD

**Issue by sknutsonsf** [shanx/django-maintenancemode#20]
The current default for the lockfile uses the __file__ location of the distributed conf.py file.
The resulting location can be under /usr/local or /usr/lib and not writable.
I'm still on Django 1.6, but I don't think it will be different in later version.

**Comment by bashu** [comment]
you can override it in settngs.py
```python
MAINTENANCE_LOCKFILE_PATH = '/path/to/lock.file'
```
