### ISSUE TITLE
Compliance with Django 1.10 middleware

### ISSUE THREAD

**Issue by Ale-** [shanx/django-maintenancemode#22]
The module don't work with newer versions of Django from 1.10, because of the changes in Middleware introduced in 1.10  —see [documentation](https://docs.djangoproject.com/en/1.10/topics/http/middleware/#upgrading-pre-django-1-10-style-middleware).

As said in the documentation I've tested to change the 'middleware.py' file, making 'MaintenanceModeMiddleware' inherit from 'django.utils.deprecation.MiddlewareMixin' instead of 'object' and everything seems fine now. It works like a charm.

**Comment by gorcsev71** [comment]
I confirm, unfortunately it does not work in django 1.10 :-(

**Comment by bashu** [comment]
@Ale- @gorcsev71 fixed in 0.11.3
