### ISSUE TITLE
Job failing on travis-ci for python 2.7

### ISSUE THREAD

**Issue by kishorkunal-raj** [shanx/django-maintenancemode#32]
Hi, 
I am running jobs on travis-ci but its been found that job is failing for python 2.7.
 
Log:
Setting environment variables from .travis.yml
$ export DJANGO="Django>=1.11,<1.12"
0.01s$ source ~/virtualenv/python2.7/bin/activate
$ python --version
Python 2.7.15
$ pip --version
pip 20.1.1 from /home/travis/virtualenv/python2.7.15/lib/python2.7/site-packages/pip (python 2.7)
before_install
7.91s$ pip install -q $DJANGO coveralls
install
0.59s$ python setup.py develop
2.33s$ python setup.py test
running test
WARNING: Testing via this command is deprecated and will be removed in a future version. Users looking for a generic test entry point independent of test runner are encouraged to use tox.
/home/travis/virtualenv/python2.7.15/lib/python2.7/site-packages/OpenSSL/crypto.py:12: CryptographyDeprecationWarning: Python 2 is no longer supported by the Python core team. Support for it is now deprecated in cryptography, and will be removed in a future release.
  from cryptography import x509
DEPRECATION: Python 2.7 reached the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 is no longer maintained. pip 21.0 will drop support for Python 2.7 in January 2021. More details about Python 2 support in pip, can be found at https://pip.pypa.io/en/latest/development/release-process/#python-2-support
/home/travis/virtualenv/python2.7.15/lib/python2.7/site-packages/OpenSSL/crypto.py:12: CryptographyDeprecationWarning: Python 2 is no longer supported by the Python core team. Support for it is now deprecated in cryptography, and will be removed in a future release.
  from cryptography import x509
DEPRECATION: Python 2.7 reached the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 is no longer maintained. pip 21.0 will drop support for Python 2.7 in January 2021. More details about Python 2 support in pip, can be found at https://pip.pypa.io/en/latest/development/release-process/#python-2-support
running egg_info
writing requirements to django_maintenancemode.egg-info/requires.txt
writing django_maintenancemode.egg-info/PKG-INFO
writing top-level names to django_maintenancemode.egg-info/top_level.txt
writing dependency_links to django_maintenancemode.egg-info/dependency_links.txt
reading manifest file 'django_maintenancemode.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
writing manifest file 'django_maintenancemode.egg-info/SOURCES.txt'
running build_ext
Creating test database for alias 'default'...
maintenancemode.tests (unittest.loader.ModuleImportFailure) ... ERROR
Destroying test database for alias 'default'...
Coverage Report:
Name                                                 Stmts   Miss  Cover
------------------------------------------------------------------------
maintenancemode/conf.py                                 10      7    30%
maintenancemode/http.py                                  3      3     0%
maintenancemode/management/commands/maintenance.py      20     20     0%
maintenancemode/middleware.py                           32     32     0%
maintenancemode/models.py                                0      0   100%
maintenancemode/utils.py                                25     23     8%
maintenancemode/views.py                                11     11     0%
------------------------------------------------------------------------
TOTAL                                                  101     96     5%
PEP8 Report:
maintenancemode/middleware.py:23:80: E501 line too long (80 > 79 characters)
maintenancemode/tests.py:36:80: E501 line too long (85 > 79 characters)
maintenancemode/tests.py:50:80: E501 line too long (89 > 79 characters)
maintenancemode/tests.py:58:80: E501 line too long (94 > 79 characters)
maintenancemode/tests.py:64:80: E501 line too long (94 > 79 characters)
maintenancemode/tests.py:69:80: E501 line too long (82 > 79 characters)
maintenancemode/tests.py:75:80: E501 line too long (100 > 79 characters)
maintenancemode/tests.py:77:80: E501 line too long (93 > 79 characters)
maintenancemode/tests.py:78:80: E501 line too long (88 > 79 characters)
maintenancemode/tests.py:84:80: E501 line too long (100 > 79 characters)
maintenancemode/tests.py:86:80: E501 line too long (93 > 79 characters)
maintenancemode/tests.py:95:80: E501 line too long (100 > 79 characters)
maintenancemode/tests.py:97:80: E501 line too long (94 > 79 characters)
maintenancemode/tests.py:106:80: E501 line too long (131 > 79 characters)
maintenancemode/tests.py:108:80: E501 line too long (93 > 79 characters)
maintenancemode/tests.py:117:80: E501 line too long (135 > 79 characters)
maintenancemode/tests.py:119:80: E501 line too long (93 > 79 characters)
maintenancemode/tests.py:128:80: E501 line too long (131 > 79 characters)
maintenancemode/tests.py:130:80: E501 line too long (94 > 79 characters)
maintenancemode/tests.py:136:80: E501 line too long (90 > 79 characters)
maintenancemode/tests.py:139:80: E501 line too long (80 > 79 characters)
maintenancemode/tests.py:141:80: E501 line too long (94 > 79 characters)
maintenancemode/tests.py:146:80: E501 line too long (84 > 79 characters)
maintenancemode/tests.py:148:80: E501 line too long (94 > 79 characters)
maintenancemode/tests.py:153:80: E501 line too long (100 > 79 characters)
maintenancemode/tests.py:156:80: E501 line too long (94 > 79 characters)
maintenancemode/tests.py:161:80: E501 line too long (101 > 79 characters)
maintenancemode/tests.py:163:80: E501 line too long (109 > 79 characters)
maintenancemode/tests.py:166:80: E501 line too long (110 > 79 characters)
maintenancemode/views.py:16:1: E402 module level import not at top of file
======================================================================
ERROR: maintenancemode.tests (unittest.loader.ModuleImportFailure)
----------------------------------------------------------------------
ImportError: Failed to import test module: maintenancemode.tests
Traceback (most recent call last):
  File "/opt/python/2.7.15/lib/python2.7/unittest/loader.py", line 254, in _find_tests
    module = self._get_module_from_name(name)
  File "/opt/python/2.7.15/lib/python2.7/unittest/loader.py", line 232, in _get_module_from_name
    __import__(name)
  File "/home/travis/build/kishorkunal-raj/django-maintenancemode/maintenancemode/tests.py", line 16, in <module>
    from maintenancemode import utils  File "/home/travis/build/kishorkunal-raj/django-maintenancemode/maintenancemodeutils.py", line 5, in <module>
from .conf import settings
  File "/home/travis/build/kishorkunal-raj/django-maintenancemode/maintenancemode/conf.py", line 6, in <module>    from appconf import AppConf
  File "/home/travis/virtualenv/python2.7.15/lib/python2.7/site-packages/django_appconf-1.0.4-py2.7.egg/appconf/__init__.py", line 1, in <module>
    from .base import AppConf  # noqa
  File "/home/travis/virtualenv/python2.7.15/lib/python2.7/site-packages/django_appconf-1.0.4-py2.7.egg/appconf/base.py", line 107
    class AppConf(metaclass=AppConfMetaClass):
                           ^
SyntaxError: invalid syntax
----------------------------------------------------------------------
Ran 1 test in 0.069s
FAILED (errors=1)
Test failed: <unittest.runner.TextTestResult run=1 errors=1 failures=0>
error: Test failed: <unittest.runner.TextTestResult run=1 errors=1 failures=0>
trThe command "python setup.py test" exited with 1.

Please look into it

**Comment by bashu** [comment]
not sure whether django-appconf still support python 2.7 or not, but I am dropping python 2.x

you can try older versions, for example `pip install django-appconf==1.0.2`
