### ISSUE TITLE
Middleware early return refactor (suggest/request for comment)

### ISSUE THREAD

**Issue by erayaydin** [shanx/django-maintenancemode#39]
https://github.com/shanx/django-maintenancemode/blob/6555e4afd9ade091a8538b1a0b2b63cff1c86d25/maintenancemode/middleware.py#L54-L66

Don't need to `else` section due to `early return`. It's can refactor like:

```python
 if DJANGO_VERSION_MAJOR >= 3 and DJANGO_VERSION_MINOR >= 2: 
     # Checks if DJANGO version is great than 3.2.0 for breaking change 
     resolver = resolvers.get_resolver(None) 
     resolve = resolver.resolve_error_handler 
     callback = resolve('503') 
     return callback(request)

 resolver = get_resolver() 
 callback, param_dict = resolver.resolve_error_handler("503") 
 return callback(request, **param_dict) 
```

Maybe it's not enough "readable". What do you think about this?

**Comment by bashu** [comment]
to @erayaydin thanks, but it doesn't improve anything, neither readability, nor performance.

**Comment by erayaydin** [comment]
I created this issue just to get the idea and maybe because it's a topic that might have been unnoticed. If it's not something that should be changed, we can close this. Maybe a `contribution guideline` will be useful. Again, thank you for your efforts on the project.
