### ISSUE TITLE
Are contributions welcome?

### ISSUE THREAD

**Issue by aqeelat** [shanx/django-maintenancemode#41]
I have a few suggestions on how to improve this package. Is this package still maintained?

**Comment by shanx** [comment]
Hey @AqeelAT thanks for checking in on this! 

@bashu lovingly took over maintenance of this package years ago and did an amazing job in getting it to where it is today. Myself, as a young dad, currently I don't have a lot of time. And professionally shifted my focus away from the web to develop firmware for 3d printers. 

So it is a question that @bashu would need to answer. Maybe he would even appreciate help with maintaining this package?

**Comment by bashu** [comment]
hey @shanx while you are online, can you transfer the project to me. Thank you and congrats :)

**Comment by shanx** [comment]
@bashu done ❤️

**Comment by aqeelat** [comment]
@shanx congrats on your fatherhood.

@bashu Let's collab on this if you're interested. I have a few ideas that I would like to see in this package.

**Comment by aqeelat** [comment]
@bashu do you prefer I open an issue for each change? Or just open PRs directly?
Also, can you please give me contributor access?

**Comment by bashu** [comment]
@AqeelAT either issue + PR or just PR.
Let me see your first PR.
