### ISSUE TITLE
Ignore URLs not working

### ISSUE THREAD

**Issue by tijs** [shanx/django-maintenancemode#5]
I'm using this neat little package in my project and it works like a charm except for the ignore URL feature. When i add any ignore URLs it seems to default to not redirecting to the 503 page at all. When i remove the MAINTENANCE_IGNORE_URLS variable everything works as expected again. This is on Django 1.3.1 and my middleware order looks like this (since that might have something to do with it?)

    MIDDLEWARE_CLASSES = (
        #'raven.contrib.django.middleware.SentryResponseErrorIdMiddleware',
        #'django.middleware.locale.LocaleMiddleware',
        'django.middleware.common.CommonMiddleware',
        'django.contrib.sessions.middleware.SessionMiddleware',
        'django.middleware.csrf.CsrfViewMiddleware',
        'django.contrib.auth.middleware.AuthenticationMiddleware',
        'django.contrib.messages.middleware.MessageMiddleware',
        'django.middleware.http.ConditionalGetMiddleware',
        'django.middleware.gzip.GZipMiddleware',
        'maintenancemode.middleware.MaintenanceModeMiddleware',
        'debug_toolbar.middleware.DebugToolbarMiddleware',
        'django.contrib.flatpages.middleware.FlatpageFallbackMiddleware',
        #'raven.contrib.django.middleware.Sentry404CatchMiddleware'
    )

**Comment by bashu** [comment]
and ``MAINTENANCE_IGNORE_URLS`` was?

**Comment by bashu** [comment]
unable to reproduce
