### ISSUE TITLE
This project needs a maintainer.

### ISSUE THREAD

**Issue by bashu** [shanx/django-maintenancemode#7]
Hi,

This repository seems to lack maintenance, I propose myself as a new maintainer.

Could you give me the right to push in your repository or just transfer it on my account in github?

Thank you

**Comment by shanx** [comment]
Hi @bashu nice that you are reaching out to take over maintenance, I see you are doing this with a lot of projects. Very nice of you!

Can you tell me what you are planning to do? I'll be happy to give over maintenance to you. What is your pypi account?

**Comment by bashu** [comment]
I am planning to resolve all pending issues / pull requests, make sure all django version from 1.4 through 1.8 are supported, add example app as reference, integrate with travis ci and so one

username: bashu

**Comment by bashu** [comment]
@shanx are you still here?

**Comment by shanx** [comment]
was away for a little while, fixing it now

**Comment by shanx** [comment]
you have right to push to the repo. what is your username on pypi? so I can give you permission to push new versions there too. thanks!

**Comment by bashu** [comment]
username: bashu

**Comment by shanx** [comment]
done! thanks brother for taking care of this package!
