### ISSUE TITLE
django 1.8 compatibility

### ISSUE THREAD

**Issue by GitRon** [shanx/django-maintenancemode#8]
Hi guys,

I tried to use the plugin with django 1.8. I get the following exception. When using django 1.7.7 everything works fine:

AttributeError: 'RegexURLResolver' object has no attribute '_resolve_special'

Exception

Stacktrace (most recent call last):

  File "maintenancemode/middleware.py", line 44, in process_request
    callback, param_dict = resolver._resolve_special('503')

Best,
Ron

**Comment by nordbit** [comment]
_resolve_special has been removed in django1.8

You can change line 44 in middleware.py with this code:
```
callback, param_dict = resolver.resolve_error_handler('503')
```
Without guarantee. Works for me. Django==1.8.1

**Comment by GitRon** [comment]
Thanks! But will someone update the package or do I need to fix it manually?

**Comment by pyMan** [comment]
I can confirm it's the right fix.

**Comment by bashu** [comment]
Hey, bugfix release will be ready either tomorrow or after tomorrow

**Comment by GitRon** [comment]
Cool!
